
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 05 17:10:56 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int MENOS = 12;
  public static final int MAYOR_IGUAL_QUE = 9;
  public static final int OR = 19;
  public static final int IGUAL = 5;
  public static final int DECIMAL = 4;
  public static final int MENOR_IGUAL_QUE = 10;
  public static final int NOT = 20;
  public static final int MAYOR_QUE = 7;
  public static final int POT = 15;
  public static final int ID = 2;
  public static final int MENOR_QUE = 8;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int DIFERENTE = 6;
  public static final int DIV = 14;
  public static final int PAR_IZQ = 16;
  public static final int error = 1;
  public static final int PAR_DER = 17;
  public static final int ENTERO = 3;
  public static final int MAS = 11;
}

